name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://kamiui.ml/E51partition2/%E2%98%86%E5%88%B7%E6%9C%BA%E5%8C%85/%E5%B0%8F%E7%B1%B3/%E7%BA%A2%E7%B1%B3K30%205G%E5%AE%98%E6%94%B9/HMK30_5G_V12.0.2.0.QGICNXM_37ed2ce056_10.0%EF%BC%88MIUI%2012%E7%A8%B3%E5%AE%9A%E7%89%88%EF%BC%89%EF%BC%88by%20East%E7%A7%91%E6%8A%80%E8%B5%84%E8%AE%AF-xiaozhao%EF%BC%89%EF%BC%882020.6.28%EF%BC%89/HMK30_5G_V12.0.2.0.QGICNXM_37ed2ce056_10.0%EF%BC%88MIUI%2012%E7%A8%B3%E5%AE%9A%E7%89%88%EF%BC%89%EF%BC%88by%20East%E7%A7%91%E6%8A%80%E8%B5%84%E8%AE%AF-xiaozhao%EF%BC%89%EF%BC%882020.6.28%EF%BC%89.zip
  ROM_NAME: MIUI For Android 10
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone Source Code
         run: git clone --recurse-submodules https://github.com/lukejacksonbristot/ErfanGSIs.git
       
       - name: Setting up Fit-GSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
              sudo sed -i '7c AB=true' url2GSI.sh
              sudo sed -i '8c Aonly=true' url2GSI.sh
       - name: Download Stock Rom & Generate A/B GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet final/GSI.zip
